config/routes.rb
GoLunch::Application.routes.draw do

  root 'welcome#index'
  resources :messages

end

app/models/message.rb
class Message < ActiveRecord::Base
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z+]\z/i

  validates_presence_of :message
  validates_format_of :email, with: VALID_EMAIL, on:create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(set_params)
    if @message.save
      ForwardMessage.send_message(@message).deliver
      redirect_to root_path, notice:"Message successfully sent"
    else
      render :new
    end
  end

  private

  def set_params
    params.require(:message).permit(:email,:message)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forward_message/send_message.text.erb
Debbie, 

you got a message from <%= @message.email %>, saying:
<%= @message.message %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">My Site</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><%=link_to "Contact Me", new_message_path %></li>
      <li class="has-dropdown">
        <a href="#">Right Button with Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
  </section>
</nav>
<%= notice %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/messages/new.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :email %>
  <%= f.input :message %>
  <%= f.submit %>
<% end %>